---
title: "St"
author: "Ali Banijamali"
---

```{r, echo=FALSE}


pal <- rainbow(5, alpha=.5) 
plot(CNET, edge.arrow.size=.2, vertex.size=10, edge.curved=.2, col=pal, vertex.color=CNET.N$Under.grad)

plot(CNET, edge.arrow.size=.2, vertex.size=10, edge.curved=.2, vertex.color=CNET.N$Department)


col <- rainbow(9, alpha=.5)
#colrs <- c("gray50", "tomato", "gold")
V(CNET)$color <- col[V(CNET)$Department]

# Compute node degrees (#links) and use that to set node size:
deg <- degree(net, mode="all")
V(net)$size <- deg*3
# We could also use the audience size value:
V(net)$size <- V(net)$audience.size*0.6

# The labels are currently node IDs.
# Setting them to NA will render no labels:
V(net)$label <- NA

# Set edge width based on weight:
E(net)$width <- E(net)$weight/6

#change arrow size and edge color:
E(net)$arrow.size <- .2
E(net)$edge.color <- "gray80"
E(net)$width <- 1+E(net)$weight/12
plot(net) 



V(CNET)
N <- V(CNET)

deg <- degree(CNET, N, mode="all")

bet <- betweenness(CNET, normalized=TRUE)

clos <- closeness(CNET, mode="all", normalized=TRUE)

V(CNET)$size <- deg+10

V(CNET)$size <- bet*300

V(CNET)$size <- clos*200

col1 <- heat.colors(9, alpha=.5)
col2 <- rainbow(9, alpha=.5)
col3 <- brewer.pal(9, "Set3")
col4 <- brewer.pal(9, "Spectral")
col5 <- brewer.pal(9, "Set1")
col6 <- c("deeppink", "khaki3", "purple3", "tomato", "chartreuse", "turquoise1", "darkgreen", "orange", "dodgerblue")

V(CNET)$color <- col1[V(CNET)$Department]
V(CNET)$color <- col2[V(CNET)$Department]
V(CNET)$color <- col3[V(CNET)$Department]
V(CNET)$color <- col4[V(CNET)$Department]
V(CNET)$color <- col5[V(CNET)$Department]
V(CNET)$color <- col6[V(CNET)$Department]

V(CNET)$frame.color <- "gray39"

E(CNET)$arrow.size <- .2
E(CNET)$color <- "gray40"
E(CNET)$curved <- .2
E(CNET)$width <- 1

plot(CNET, edge.arrow.size=.2, edge.curved=.2, vertex.color=CNET.N$Under.grad)

plot(CNET, edge.arrow.size=.2, edge.curved=.2, vertex.color=CNET.N$Under.grad)

plot(CNET)

A <- erdos.renyi.game(100, 0.1)

plot(A)
```


```{r}
# go from green through yellow to red with no blue
 x<-rnorm(20)
 y<-rnorm(20)
 # use y for the color scale
 plot(x,y,col=color.scale(y,c(0,1,1),c(1,1,0),0),main="Color scale plot",
  pch=16,cex=2)
```





```{r, echo=FALSE}
#Based on Degree
deg <- degree(CNET, mode="all")

V(CNET)$color <- "khaki2"
V(CNET)$frame.color <- "gray80"
V(CNET)$size <- deg+10

E(CNET)$arrow.size <- .2
E(CNET)$color <- "tomato1"
E(CNET)$curved <- .2
E(CNET)$width <- 1

plot(CNET, sub="Size of The nodes Based on Their Degrees")

#Based on Betweenness
bet <- betweenness(CNET, normalized=TRUE)

bet.f <- as.data.frame(bet)
bet.f.sc <- as.data.frame(as.integer(bet*1000+1))

colnames(bet.f) <- "bet"
colnames(bet.f.sc) <- "bet.sc"

CNET.N[,c(4)] <- bet.f
CNET.N[,c(5)] <- bet.f.sc

CNET <- graph.data.frame(CNET.E, CNET.N, directed = TRUE)

#bet.f.s <- as.data.frame(sort(bet.f$bet)) 8

a <- sort(V(CNET)$bet.sc, decreasing = TRUE)
#ba <- as.data.frame(a)
#col3 <- brewer.pal(8, "Blues")
#cc <- col3[a]
#V(CNET)$color <- cc[V(CNET)$bet]

d <- color.scale(V(CNET)$bet.sc, cs1=c(1,1),0)
d <- color.scale(V(CNET)$bet.sc, cs3=c(0,1))

V(CNET)$color <- d[V(CNET)$bet.sc]
plot(CNET)
colorbar.plot(x, y, strip, strip.width = 0.1, strip.length = 4 * strip.width, 
zrange = NULL, adj.x = 0.5, adj.y = 0.5, col = tim.colors(256), 
horizontal = TRUE, ...)


V(CNET)$frame.color <- "gray80"
V(CNET)$size <- 15

E(CNET)$arrow.size <- .2
E(CNET)$color <- "gray50"
E(CNET)$curved <- .2
E(CNET)$width <- 1

plot(CNET, sub="Size of The nodes Based on Their Degrees")
```


```{r}

distance <- function(sq) {
  sq2 <- dist(CDM, method = "manhattan")
}
  dist(CDM, method = "manhattan")

GenSeq <- function(sq) {
  idx <- seq(2, NROW(CDM)-1, by=1)
  ChangePoints <- sample(idx, size=2, replace=FALSE)
  tmp <- sq[ChangePoints[1]]
  sq[ChangePoints[1]] <- sq[ChangePoints[2]]
  sq[ChangePoints[2]] <- tmp
  return(as.numeric(sq))
}

distance <- function(sq) 
  {  # Target function
  sq2 <- embed(sq, 2)
  return(as.numeric(sum(CityDistMatx[cbind(sq2[,2],sq2[,1])])))
}

```
